<h1>Injectables</h1>

<p>
    <?= $block->getViewModel()->getSupply()->getSupplier()->getCode(); ?>
</p>

<p>
    <?= $block->getViewModel()->getDemand()->getSupplier()->getCode(); ?><!--the demand class can also excess the code because this code is injectable-->
</p>

<p>
    <?= $block->getViewModel()->getSupply()->getItem()->getCode(); ?><!--this will have different value because this is non injectable also this will not modidy existing code-->
</p>

<p>
    <?= $block->getViewModel()->getDemand()->getSupplier()->getCode(); ?>
</p>